CREATE TABLE IF NOT EXISTS persons
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid varchar(40) not null,
    name varchar(255) not null,
    created_at timestamp not null,
    updated_at timestamp not null
);